### ISSUE TITLE
First letter as a special character causing problems

### ISSUE THREAD

**Issue by Keodo** [Sentilix/sota-classic#1]
We have a character in our guild whose name starts with the letter Ö

This appears to be breaking the addon's ability to add and subtract DKP automatically. He is the only member of the guild who we have to apply DKP to manually. Is this something that can be fixed?

**Comment by Sentilix** [comment]
I'll try to make a character with Ö and see if I can fix it.
Thanks for the report.

**Comment by Sentilix** [comment]
Great, I have fixed the bug in release 0.5.3 which is available now.

**Comment by Keodo** [comment]
Awesome, thanks so much for the quick fix!
